### ISSUE TITLE
Project might have to be renamed.

### ISSUE THREAD

**Issue by jorisvddonk** [kmeaw/ultraworm#3]
From the PuppyGames blog (http://www.puppygames.net/blog/?p=914):

"You may also absolutely not use the name “Revenge of the Titans”, “Puppygames”, or “Shaven Puppy Ltd” when redistributing any derivative works without our express permission, as that’d again be stepping on our trademarks."

I guess this means that we might have to rename these repositories?

**Comment by zhuowei** [comment]
Maybe it can be renamed to Ultraworm, the codename for the game?

**Comment by jorisvddonk** [comment]
Yeah, that seems to be a properish name for it, for now..
